stages:
  - build-x86
  - build-x64
  - artifacts

variables:
  build_path: "$CI_PROJECT_DIR/src/"
  output_path: "$CI_PROJECT_DIR/output/"

cache:
   key: ${CI_COMMIT_REF_SLUG}
   paths:
     - .tmp/

before_script:
  - cd $build_path

build-x86:
  stage: build-x86
  script:
    - powershell -File $CI_PROJECT_DIR\build.ps1 Compile --Configuation $Configuration --TargetPlatform x86

artifacts-x86:
  stage: build-x86
  variables:
    GIT_STRATEGY: "none"
  script:
    - powershell -File $CI_PROJECT_DIR\build.ps1 Artifacts --TargetPlatform x86
  cache:
    key: "${CI_COMMIT_SHORT_SHA}-x86"
    paths:
      - output/*.zip

build-x64:
  stage: build-x64
  script:
    - powershell -File $CI_PROJECT_DIR\build.ps1 Compile --Configuation $Configuration --TargetPlatform x64

artifacts-x64:
  stage: build-x64
  variables:
    GIT_STRATEGY: "none"
  script:
    - powershell -File $CI_PROJECT_DIR\build.ps1 Artifacts --TargetPlatform x64
  cache:
    key: "${CI_COMMIT_SHORT_SHA}-x64"
    paths:
      - output/*.zip

artifacts:
  stage: artifacts
  script: echo "Publish artifacts"
  cache:
    - key: "${CI_COMMIT_SHORT_SHA}-x86"
      paths:
        - output/*.zip
    - key: "${CI_COMMIT_SHORT_SHA}-x64"
      paths:
        - output/*.zip
  artifacts:
    paths:
      - output/*