variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - artifacts

build_master:
  only:
    - master
  stage: build
  script:
  - .\build.ps1 -target Restore
  - .\build.ps1 -target Compile -configuration Release

build:
  except:
    - master
  stage: build
  script:
  - .\build.ps1 -target Restore
  - .\build.ps1 -target Compile -configuration Debug

prepare_artifacts:
  variables:
    GIT_STRATEGY: none
  only:
    - master
    - develop
    - tags
  stage: artifacts
  script:
  - $env:$CI_PROJECT_DIR\build.ps1 -target CopyArtifacts
  artifacts:
    when: on_success
    name: "dotnet_diskcover"
    paths:
     - $env:CI_PROJECT_DIR/artifacts/dotnet_diskcover.zip
    expire_in: 1 week